// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class CartRoomItem
{
    public int Id { get; set; }

    public int RoomId { get; set; }

    public DateTime CheckInDate { get; set; }

    public DateTime CheckOutDate { get; set; }

    public int? MemberId { get; set; }

    public string Remark { get; set; }

    public string Phone { get; set; }

    public virtual Room Room { get; set; }
}